[package]
name = "Sub-Ocaml-REPL"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "14.0.0"
anyhow = "1.0"
Sub-OCaml = { git = "https://github.com/Neotamandua/Sub-OCaml" }